fastlane_require 'dotenv'

platform :android do
    before_all do
        Dotenv.overload '.env'
    end

    desc "Build lane"
    lane :build do
        sh("fvm flutter build appbundle --release")
    end

    #desc "Android Firebase app distribution"
    #lane :deploy_to_firebase do
    #    firebase_app_distribution(
    #        app: "1:850407421869:android:d532e6c175eb2bd826d324",
    #        groups: "devs",
    #        release_notes: "Initial test version of the app",
    #        android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab"
    #    )
    #end

    desc "Android App Center distribution"
    lane :deploy_to_appcenter do
        appcenter_upload(
            destinations: "devs",
            api_token: ENV["APP_CENTER_TOKEN"],
            owner_name: "seuxbaptiste-gmail.com",
            owner_type: "user", # Default is user - set to organization for appcenter organizations
            app_name: "TRAMS-android",
            file: "../build/app/outputs/bundle/release/app-release.aab",
            notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
        )
    end

    desc "Android App Center distribution test"
    lane :deploy_to_appcenter_test do
        appcenter_upload(
            destinations: "devs, testers",
            api_token: ENV["APP_CENTER_TOKEN"],
            owner_name: "seuxbaptiste-gmail.com",
            owner_type: "user", # Default is user - set to organization for appcenter organizations
            app_name: "TRAMS-android",
            file: "../build/app/outputs/bundle/release/app-release.aab",
            notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
        )
    end

    desc "Android App Playstore"
    lane :deploy_to_playstore do
        upload_to_play_store(
            aab: "../build/app/outputs/bundle/release/app-release.aab",
            changes_not_sent_for_review: true,
            track: "internal"
        )
  end
end
